POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "email": "admin1@example.com",
  "phone": "0771234567",
  "password": "123456789",
  "roleName": "admin"
}

### Login 
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "admin1@example.com",
  "password": "123456789"
}

### Mobile Login (imitate mobile client)
POST http://localhost:5000/api/auth/login
Content-Type: application/json
X-Client-Type: mobile

{
  "email": "admin1@example.com",
  "password": "123456789"
}


### visit admin-page
GET http://localhost:5000/api/admin/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzUxNzM5MzM4LCJleHAiOjE3NTE3NDAyMzh9.9iXJcPxm-8aYPDFR_hCfobekZUTtvkSF5oRSlOuy0AY

### visit admin-stats
GET http://localhost:5000/api/admin/stats
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Mywicm9sZSI6ImFkbWluIiwiaWF0IjoxNzUxNzM2MjgxLCJleHAiOjE3NTE3MzcxODF9.ZZP0oOWIkHvOmFyJz5yeYmHNHOTUnEUXyFKUOm4Jpq8


### visit user-page
GET http://localhost:5000/api/user/book-service
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwicm9sZSI6InVzZXIiLCJpYXQiOjE3NTEwNjExNDEsImV4cCI6MTc1MTA2MjA0MX0.f_aoRETCavvNAZi_bnpF8kGBSFUG0w9gJUBo8oEjvkg

### visit worker-page
GET http://localhost:5000/api/worker/jobs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Mywicm9sZSI6ImFkbWluIiwiaWF0IjoxNzUxMDU0ODA1LCJleHAiOjE3NTEwNTU3MDV9.LLVNuv8bpj_-WOpo1B9i4l_jcQfjf60SsrrD6FS9DSk

### refresh token
POST http://localhost:5000/api/auth/refresh
Content-Type: application/json

{"refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzUxNzM5NzY4LCJleHAiOjE3NTIzNDQ1Njh9.H67f2JQCEGNV_aiCatleCqdCC2j0u1z-YaK40MJvwfE"}

### logout
POST http://localhost:5000/api/auth/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzUxNzM5NzY4LCJleHAiOjE3NTE3NDA2Njh9.b9TCYtGby3zjH429VFuTaj35JTzqML6KWlsf0IGlkEM

